<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>404 NOT FOUND</title>

    <style>
        * {margin: 0; padding: 0;}
        #wrap {
            margin: 0 auto;
            width: 400px;
            text-align: center; font-size: 60px; margin-top: 6%;
        }

        #err-icon {
            background: url("/static/img/404_icon.png") no-repeat;
            width: 300px;
            height: 240px;
            margin-left: 50px;
            background-size: cover;
        }

        #wrap .code {
            color: #666; font-size: 20px;
        }
    </style>
</head>

<body>

    <div id="wrap">
        <div id="err-icon"></div>
        <p>没有找到页面</p>
        <p class="code">404 NOT FOUND</p>
    </div>

</body>
</html>
